apiVersion: v1
kind: Service
metadata:
  labels:
    app: webserver
  name: webserver-service
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30001
  selector:
    app: webserver
